---
- name: Run apt update on devices using apt
  hosts: debian
  become: true
  become_method: sudo

  tasks:

#Tested on Raspberry Pi OS and Ybuntu for Raspberry Pi

    - name: run apt update
      apt: 
        update_cache: yes

    - name: run apt upgrade
      apt:
        name: "*"
        state: latest

#Remove autoremove if you prefer to do this manually

    - name: run autoremove
      apt:
        autoremove: yes

#Tested on pi running Fedora 32

- name: DNF refresh and upgrade
  hosts: raspfedora
  become: true
  become_method: sudo

  tasks:

    - name: run dnf 
      dnf:
        name: '*'
        state: latest
