---
- name: Initial configuration of a debian host
  hosts: "{{ hosts | default('none') }}"
  become: true
  become_method: sudo

  tasks:

    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python
      raw: apt -y update && apt install -y python-minimal
      when: check_python.rc != 0

    - name: Update cache
      apt: 
        update_cache: yes
      when: check_python.rc == 0

    - name: Upgrade packages
      apt:
        name: "*"
        state: latest

    - name: Install startup packages
      apt:
        pkg:
        - ntp
        - apt-utils
        - dialog
        - python3

    - name: run autoremove
      apt:
        autoremove: yes

    - name: Create /etc/ntp directory
      file:
        path: /etc/ntp
        state: directory

    - name: Remove keys file
      ansible.builtin.file:
        path: "/etc/ntp/keys"
        state: absent
      become: yes

    - name: Create keys file
      ansible.builtin.file:
        path: "/etc/ntp/keys"
        state: touch
        mode: u=rw,g=r
      become: yes

    - name: Add keys to /etc/ntp/keys file
      blockinfile:
        path: "/etc/ntp/keys"
        block: |
          10 SHA1 e7d4d699f280e67cbac2235dab09aef2188cd06b #Some SHA Key
          20 SHA1 927011552cd2e45aaab60e6929bc644ac16a125e #Some other SHA Key
      become: yes

    - name: Update trustedkeys in ntp.conf
      blockinfile:
        path: "/etc/ntp.conf"
        block: |
          server 192.168.1.10 key 10
          server 192.168.1.20 key 20
          keys /etc/ntp/keys
          trustedkey 10 20
      become: yes

    - name: Remove default pools
      ansible.builtin.lineinfile:
        path: "/etc/ntp.conf"
        regexp: '^pool'
        state: absent
      become: yes

    - name: Restart ntp
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: ntp
      become: yes
